### ISSUE TITLE
Too many resolution errors!

### ISSUE THREAD

**Issue by rnleach** [aBothe/D_Parser#180]
I'm trying to use Mono-D on windows and sometimes on Mac. I keep getting this error EVERY TIME I use the '.' operator on certain objects. Some objects it errors on, others it does not. But it is consistent about which ones it does throw the error for.  Some are from classes/structs I've defined, and others are for classes/structs in the phobos library.

This error makes Mono-D almost unusable. (At least for this source file, which compiles and runs fine.)

I downloaded and installed Mono-D per the instructions on the [dlang.org Wiki](http://wiki.dlang.org/Mono-D)

I'm running Xamarin Studio 5.6.2 build 5 and the Mono-D plugin 2.5.4. I use the alpha channel for Xamarin updates as suggested on the install instructions, but when I saw this I rolled back to the beta and then stable version. It made no difference.

```
System.AggregateException: One or more errors occurred. ---> D_Parser.Resolver.TooManyResolutionErrors: Too many resolution errors!
   at D_Parser.Resolver.ResolutionContext.LogError(ResolutionError err)
   at D_Parser.Resolver.ResolutionContext.CheckForSingleResult[T](IEnumerable`1 results, ISyntaxRegion td)
   at D_Parser.Resolver.ExpressionSemantics.Evaluation.Visit(PostfixExpression_Access ex)
   at D_Parser.Dom.Expressions.PostfixExpression_Access.Accept[R](ExpressionVisitor`1 vis)
   at D_Parser.Resolver.ExpressionSemantics.Evaluation.Visit(EqualExpression x)
   at D_Parser.Dom.Expressions.EqualExpression.Accept[R](ExpressionVisitor`1 vis)
   at D_Parser.Resolver.ExpressionSemantics.Evaluation.EvaluateValue(IExpression x, AbstractSymbolValueProvider vp)
   at D_Parser.Resolver.ExpressionSemantics.Evaluation.EvaluateValue(IExpression x, ResolutionContext ctxt, Boolean lazyVariableValueEvaluation)
   at D_Parser.Resolver.ConditionalCompilationFlags.IsMatching(StaticIfCondition sc, ResolutionContext ctxt)
   at D_Parser.Resolver.ConditionalCompilation.ConditionSet.IsMatching(DeclarationCondition dc, ResolutionContext ctxt)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.MatchesCompilationConditions(DNode n)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.CanHandleNode(DNode dn, MemberFilter VisibleMembers, Boolean isBaseClass, Boolean isMixinAst, Boolean takeStaticChildrenOnly, Boolean publicImports, Boolean scopeIsInInheritanceHierarchy)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.scanChildren(DBlockNode curScope, MemberFilter VisibleMembers, Boolean publicImports, Boolean isBaseClass, Boolean isMixinAst, Boolean takeStaticChildrenOnly, Boolean scopeIsInInheritanceHierarchy, DSymbol resolvedCurScope)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.DeepScanClass(UserDefinedType udt, MemberFilter vis, Boolean resolveBaseClassIfRequired)
   at D_Parser.Resolver.ASTScanner.SingleNodeNameScan.SearchChildrenAndResolve(ResolutionContext ctxt, DSymbol t, Int32 nameHash, ISyntaxRegion idObject)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.ResolveFurtherTypeIdentifier(Int32 nextIdentifierHash, IEnumerable`1 resultBases, ResolutionContext ctxt, ISyntaxRegion typeIdObject, Boolean ufcsItem)
   at D_Parser.Resolver.TypeResolution.TemplateInstanceHandler.TryGetImplicitProperty(TemplateType template, ResolutionContext ctxt)
   at D_Parser.Resolver.TypeResolution.TemplateInstanceHandler.DeduceParamsAndFilterOverloads(IEnumerable`1 rawOverloadList, IEnumerable`1 givenTemplateArguments, Boolean isMethodCall, ResolutionContext ctxt)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.GetOverloads(TemplateInstanceExpression tix, ResolutionContext ctxt, IEnumerable`1 resultBases, Boolean deduceParameters)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.Visit(TemplateInstanceExpression tix)
   at D_Parser.Dom.Expressions.TemplateInstanceExpression.Accept[R](ExpressionVisitor`1 vis)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.EvaluateType(IExpression x, ResolutionContext ctxt, Boolean tryReturnMethodReturnType)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.ResolveSingle(ITypeDeclaration declaration, ResolutionContext ctxt)
   at D_Parser.Resolver.TypeResolution.TemplateInstanceHandler.PreResolveTemplateArgs(TemplateInstanceExpression tix, ResolutionContext ctxt)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.GetOverloads(TemplateInstanceExpression tix, ResolutionContext ctxt, IEnumerable`1 resultBases, Boolean deduceParameters)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.Visit(TemplateInstanceExpression tix)
   at D_Parser.Dom.Expressions.TemplateInstanceExpression.Accept[R](ExpressionVisitor`1 vis)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.EvaluateType(IExpression x, ResolutionContext ctxt, Boolean tryReturnMethodReturnType)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.ResolveSingle(ITypeDeclaration declaration, ResolutionContext ctxt)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.GetMethodReturnType(DMethod method, ResolutionContext ctxt)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.NodeMatchHandleVisitor.Visit(DMethod m)
   at D_Parser.Dom.DMethod.Accept[R](NodeVisitor`1 vis)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.HandleNodeMatch(INode m, ResolutionContext ctxt, AbstractType resultBase, ISyntaxRegion typeBase, NodeMatchHandleVisitor vis)
   at D_Parser.Resolver.TypeResolution.UFCSResolver.HandleMethod(DMethod dm, MemberSymbol alreadyResolvedMethod)
   at D_Parser.Resolver.TypeResolution.UFCSResolver.HandleItem(INode n)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.scanChildren(DBlockNode curScope, MemberFilter VisibleMembers, Boolean publicImports, Boolean isBaseClass, Boolean isMixinAst, Boolean takeStaticChildrenOnly, Boolean scopeIsInInheritanceHierarchy, DSymbol resolvedCurScope)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.StatementHandler.VisitImport(Import imp)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.StatementHandler.Visit(ImportStatement impStmt)
   at D_Parser.Dom.ImportStatement.Accept[R](StatementVisitor`1 vis)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.StatementHandler.Visit(DBlockNode dbn)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.StatementHandler.Visit(DModule dbn)
   at D_Parser.Dom.DModule.Accept[R](NodeVisitor`1 vis)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.scanChildren(DBlockNode curScope, MemberFilter VisibleMembers, Boolean publicImports, Boolean isBaseClass, Boolean isMixinAst, Boolean takeStaticChildrenOnly, Boolean scopeIsInInheritanceHierarchy, DSymbol resolvedCurScope)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.ScanBlock(IBlockNode curScope, CodeLocation Caret, MemberFilter VisibleMembers, Boolean publicImportsOnly)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.ScanBlockUpward(IBlockNode curScope, CodeLocation Caret, MemberFilter VisibleMembers)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.IterateThroughScopeLayers(CodeLocation Caret, MemberFilter VisibleMembers)
   at D_Parser.Resolver.TypeResolution.UFCSResolver.TryResolveUFCS(ISemantic firstArgument, Int32 nameHash, CodeLocation nameLoc, ResolutionContext ctxt, ISyntaxRegion nameSr)
   at D_Parser.Completion.Providers.MemberCompletionProvider.<>c__DisplayClass4.<GenUfcsAndStaticProperties>b__3()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at D_Parser.Completion.CodeCompletion.DoTimeoutableCompletionTask(ICompletionDataGenerator cdgen, ResolutionContext ctxt, Action ac, Int32 timeout)
   at D_Parser.Completion.Providers.MemberCompletionProvider.GenUfcsAndStaticProperties(AbstractType t)
   at D_Parser.Completion.Providers.MemberCompletionProvider.VisitClassType(ClassType t)
   at D_Parser.Resolver.ClassType.Accept(IResolvedTypeVisitor vis)
   at D_Parser.Completion.Providers.MemberCompletionProvider.VisitMemberSymbol(MemberSymbol mrr)
   at D_Parser.Resolver.MemberSymbol.Accept(IResolvedTypeVisitor vis)
   at D_Parser.Completion.Providers.MemberCompletionProvider.BuildCompletionDataInternal(IEditorData Editor, Char enteredChar)
   at D_Parser.Completion.CodeCompletion.GenerateCompletionData(IEditorData editor, ICompletionDataGenerator completionDataGen, Char triggerChar, Boolean alreadyCheckedCompletionContext)
   at MonoDevelop.D.Completion.DCodeCompletionSupport.BuildCompletionData(Document EditorDocument, DModule SyntaxTree, CodeCompletionContext ctx, CompletionDataList l, Char triggerChar)
   at MonoDevelop.D.DEditorCompletionExtension.HandleCodeCompletion(CodeCompletionContext completionContext, Char triggerChar, Int32& triggerWordLength)
   at MonoDevelop.Ide.Gui.Content.CompletionTextEditorExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.D.DEditorCompletionExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.Ide.Gui.Content.TextEditorExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.D.Formatting.Indentation.DTextEditorIndentation.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.Ide.Gui.Content.TextEditorExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.Ide.Gui.Content.TextEditorExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.Ide.Gui.Content.TextEditorExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.Ide.Gui.Content.TextEditorExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.Debugger.ExceptionCaughtTextEditorExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.Ide.Gui.Content.TextEditorExtension.KeyPress(Key key, Char keyChar, ModifierType modifier)
   at MonoDevelop.SourceEditor.ExtensibleTextEditor.ExtensionKeyPress(Key key, UInt32 ch, ModifierType state)
---> (Inner Exception #0) D_Parser.Resolver.TooManyResolutionErrors: Too many resolution errors!
   at D_Parser.Resolver.ResolutionContext.LogError(ResolutionError err)
   at D_Parser.Resolver.ResolutionContext.CheckForSingleResult[T](IEnumerable`1 results, ISyntaxRegion td)
   at D_Parser.Resolver.ExpressionSemantics.Evaluation.Visit(PostfixExpression_Access ex)
   at D_Parser.Dom.Expressions.PostfixExpression_Access.Accept[R](ExpressionVisitor`1 vis)
   at D_Parser.Resolver.ExpressionSemantics.Evaluation.Visit(EqualExpression x)
   at D_Parser.Dom.Expressions.EqualExpression.Accept[R](ExpressionVisitor`1 vis)
   at D_Parser.Resolver.ExpressionSemantics.Evaluation.EvaluateValue(IExpression x, AbstractSymbolValueProvider vp)
   at D_Parser.Resolver.ExpressionSemantics.Evaluation.EvaluateValue(IExpression x, ResolutionContext ctxt, Boolean lazyVariableValueEvaluation)
   at D_Parser.Resolver.ConditionalCompilationFlags.IsMatching(StaticIfCondition sc, ResolutionContext ctxt)
   at D_Parser.Resolver.ConditionalCompilation.ConditionSet.IsMatching(DeclarationCondition dc, ResolutionContext ctxt)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.MatchesCompilationConditions(DNode n)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.CanHandleNode(DNode dn, MemberFilter VisibleMembers, Boolean isBaseClass, Boolean isMixinAst, Boolean takeStaticChildrenOnly, Boolean publicImports, Boolean scopeIsInInheritanceHierarchy)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.scanChildren(DBlockNode curScope, MemberFilter VisibleMembers, Boolean publicImports, Boolean isBaseClass, Boolean isMixinAst, Boolean takeStaticChildrenOnly, Boolean scopeIsInInheritanceHierarchy, DSymbol resolvedCurScope)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.DeepScanClass(UserDefinedType udt, MemberFilter vis, Boolean resolveBaseClassIfRequired)
   at D_Parser.Resolver.ASTScanner.SingleNodeNameScan.SearchChildrenAndResolve(ResolutionContext ctxt, DSymbol t, Int32 nameHash, ISyntaxRegion idObject)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.ResolveFurtherTypeIdentifier(Int32 nextIdentifierHash, IEnumerable`1 resultBases, ResolutionContext ctxt, ISyntaxRegion typeIdObject, Boolean ufcsItem)
   at D_Parser.Resolver.TypeResolution.TemplateInstanceHandler.TryGetImplicitProperty(TemplateType template, ResolutionContext ctxt)
   at D_Parser.Resolver.TypeResolution.TemplateInstanceHandler.DeduceParamsAndFilterOverloads(IEnumerable`1 rawOverloadList, IEnumerable`1 givenTemplateArguments, Boolean isMethodCall, ResolutionContext ctxt)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.GetOverloads(TemplateInstanceExpression tix, ResolutionContext ctxt, IEnumerable`1 resultBases, Boolean deduceParameters)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.Visit(TemplateInstanceExpression tix)
   at D_Parser.Dom.Expressions.TemplateInstanceExpression.Accept[R](ExpressionVisitor`1 vis)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.EvaluateType(IExpression x, ResolutionContext ctxt, Boolean tryReturnMethodReturnType)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.ResolveSingle(ITypeDeclaration declaration, ResolutionContext ctxt)
   at D_Parser.Resolver.TypeResolution.TemplateInstanceHandler.PreResolveTemplateArgs(TemplateInstanceExpression tix, ResolutionContext ctxt)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.GetOverloads(TemplateInstanceExpression tix, ResolutionContext ctxt, IEnumerable`1 resultBases, Boolean deduceParameters)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.Visit(TemplateInstanceExpression tix)
   at D_Parser.Dom.Expressions.TemplateInstanceExpression.Accept[R](ExpressionVisitor`1 vis)
   at D_Parser.Resolver.ExpressionSemantics.ExpressionTypeEvaluation.EvaluateType(IExpression x, ResolutionContext ctxt, Boolean tryReturnMethodReturnType)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.ResolveSingle(ITypeDeclaration declaration, ResolutionContext ctxt)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.GetMethodReturnType(DMethod method, ResolutionContext ctxt)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.NodeMatchHandleVisitor.Visit(DMethod m)
   at D_Parser.Dom.DMethod.Accept[R](NodeVisitor`1 vis)
   at D_Parser.Resolver.TypeResolution.TypeDeclarationResolver.HandleNodeMatch(INode m, ResolutionContext ctxt, AbstractType resultBase, ISyntaxRegion typeBase, NodeMatchHandleVisitor vis)
   at D_Parser.Resolver.TypeResolution.UFCSResolver.HandleMethod(DMethod dm, MemberSymbol alreadyResolvedMethod)
   at D_Parser.Resolver.TypeResolution.UFCSResolver.HandleItem(INode n)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.scanChildren(DBlockNode curScope, MemberFilter VisibleMembers, Boolean publicImports, Boolean isBaseClass, Boolean isMixinAst, Boolean takeStaticChildrenOnly, Boolean scopeIsInInheritanceHierarchy, DSymbol resolvedCurScope)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.StatementHandler.VisitImport(Import imp)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.StatementHandler.Visit(ImportStatement impStmt)
   at D_Parser.Dom.ImportStatement.Accept[R](StatementVisitor`1 vis)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.StatementHandler.Visit(DBlockNode dbn)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.StatementHandler.Visit(DModule dbn)
   at D_Parser.Dom.DModule.Accept[R](NodeVisitor`1 vis)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.scanChildren(DBlockNode curScope, MemberFilter VisibleMembers, Boolean publicImports, Boolean isBaseClass, Boolean isMixinAst, Boolean takeStaticChildrenOnly, Boolean scopeIsInInheritanceHierarchy, DSymbol resolvedCurScope)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.ScanBlock(IBlockNode curScope, CodeLocation Caret, MemberFilter VisibleMembers, Boolean publicImportsOnly)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.ScanBlockUpward(IBlockNode curScope, CodeLocation Caret, MemberFilter VisibleMembers)
   at D_Parser.Resolver.ASTScanner.AbstractVisitor.IterateThroughScopeLayers(CodeLocation Caret, MemberFilter VisibleMembers)
   at D_Parser.Resolver.TypeResolution.UFCSResolver.TryResolveUFCS(ISemantic firstArgument, Int32 nameHash, CodeLocation nameLoc, ResolutionContext ctxt, ISyntaxRegion nameSr)
   at D_Parser.Completion.Providers.MemberCompletionProvider.<>c__DisplayClass4.<GenUfcsAndStaticProperties>b__3()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by rnleach** [comment]
This is almost 7 years old! I'm going to close the issue unless someone else wants to reopen it.
